"""Export the authoritative Pydantic Scene JSON contract for Remotion code generation."""

import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from app.schemas.scene import VideoProject  # noqa: E402

OUTPUT = ROOT / "packages" / "remotion-templates" / "schema" / "scene-1.0.0.json"
ZOD_OUTPUT = ROOT / "packages" / "remotion-templates" / "src" / "schema.ts"


def main() -> None:
    """Write the versioned render-contract JSON Schema deterministically."""

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        json.dumps(VideoProject.model_json_schema(by_alias=True), ensure_ascii=False, indent=2) + "\n"
    )
    ZOD_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    ZOD_OUTPUT.write_text(
        "// Generated by scripts/generate_scene_schema.py; do not edit manually.\n"
        "import { convertJsonSchemaToZod } from 'zod-from-json-schema';\n"
        "import sceneJsonSchema from '../schema/scene-1.0.0.json';\n\n"
        "export const videoProjectSchema = convertJsonSchemaToZod(sceneJsonSchema as never);\n"
        "export type VideoProjectProps = unknown;\n"
    )


if __name__ == "__main__":
    main()
